"""UI constants"""

# Window dimensions
WINDOW_WIDTH = 1400
WINDOW_HEIGHT = 900
MIN_WIDTH = 1000
MIN_HEIGHT = 600

# Navigation rail width
NAV_RAIL_WIDTH = 200

# Icon sizes
ICON_SIZE_SMALL = 16
ICON_SIZE_MEDIUM = 24
ICON_SIZE_LARGE = 32

# Font sizes
FONT_SIZE_SMALL = 12
FONT_SIZE_MEDIUM = 14
FONT_SIZE_LARGE = 16
FONT_SIZE_TITLE = 20
FONT_SIZE_HEADING = 24

# Z-index
Z_INDEX_MODAL = 1000
Z_INDEX_DROPDOWN = 100
Z_INDEX_CARD = 10

